name: mapwf
channels:
- conda-forge
dependencies:
- python=3.7.10
- ipython=7.22.0
- geopandas=0.9.0
- ipywidgets=7.6.3
- requests=2.25.1
- jupyter_client=6.1.12
- jupyter_core=4.7.1
- notebook=6.3.0
- pip:
  - folium==0.12.1
